# Default values for squidguard-elk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: muenchhausen/docker-squidguard
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: squidguard
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  squidguardport: 3128
  kibanaPort: 5601
  elasticsearchPort: 9200
  logstashPort: 5000
  logstashInputPort: 5044
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
squidguard:
  WPAD_IP: "192.168.10.11"
  WPAD_NOPROXY_NET: "192.168.0.0"
  WPAD_NOPROXY_MASK: "255.255.0.0"
  UPDATE_BLACKLIST_URL: "http://www.shallalist.de/Downloads/shallalist.tar.gz"
  SQUID_CONFIG_SOURCE: "/custom-config"
